<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="astoleru" lastModifiedBy="astoleru" checksumTest="true" creationDate="28/09/2016 14:43:23 +0300" engineType="DML" lastModifiedDate="28/09/2016 14:44:28 +0300" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/bdoc1.dmlflw"/>
   </mappingInformations>
</project>